"""Repository protocols — interfaces implemented by the infrastructure layer.

Following the dependency-inversion principle, services depend on these
protocols, never on concrete SQLAlchemy implementations.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from nationcraft.domain.entities import (
    Alliance,
    Building,
    Country,
    Diplomacy,
    GameEvent,
    MarketOrder,
    Mission,
    Notification,
    Player,
    Region,
    ResearchNode,
    ResourceStock,
    Unit,
    War,
    World,
)


@runtime_checkable
class IWorldRepository(Protocol):
    async def get(self, world_id: int) -> World | None: ...
    async def get_by_slug(self, slug: str) -> World | None: ...
    async def list_open(self) -> list[World]: ...
    async def list_all(self) -> list[World]: ...
    async def create(self, **kwargs: Any) -> World: ...
    async def update(self, world: World) -> World: ...
    async def delete(self, world_id: int) -> bool: ...


@runtime_checkable
class IPlayerRepository(Protocol):
    async def get(self, player_id: int) -> Player | None: ...
    async def get_by_telegram(self, telegram_id: int) -> Player | None: ...
    async def list_by_world(self, world_id: int) -> list[Player]: ...
    async def create(self, **kwargs: Any) -> Player: ...
    async def update(self, player: Player) -> Player: ...
    async def ban(self, player_id: int) -> bool: ...


@runtime_checkable
class ICountryRepository(Protocol):
    async def get(self, country_id: int) -> Country | None: ...
    async def list_by_world(self, world_id: int) -> list[Country]: ...
    async def list_available_in_world(self, world_id: int) -> list[Country]: ...
    async def create(self, **kwargs: Any) -> Country: ...
    async def update(self, country: Country) -> Country: ...
    async def assign_player(self, country_id: int, player_id: int) -> Country: ...


@runtime_checkable
class IResourceRepository(Protocol):
    async def get(self, stock_id: int) -> ResourceStock | None: ...
    async def list_by_country(self, country_id: int) -> list[ResourceStock]: ...
    async def get_amount(self, country_id: int, key: str) -> float: ...
    async def adjust(self, country_id: int, key: str, delta: float) -> float: ...
    async def set_amount(self, country_id: int, key: str, amount: float) -> float: ...
    async def bulk_adjust(self, country_id: int, deltas: dict[str, float]) -> dict[str, float]: ...


@runtime_checkable
class IBuildingRepository(Protocol):
    async def list_by_country(self, country_id: int) -> list[Building]: ...
    async def create(self, **kwargs: Any) -> Building: ...
    async def update(self, building: Building) -> Building: ...
    async def delete(self, building_id: int) -> bool: ...


@runtime_checkable
class IResearchRepository(Protocol):
    async def list_by_country(self, country_id: int) -> list[ResearchNode]: ...
    async def get(self, country_id: int, key: str) -> ResearchNode | None: ...
    async def upsert(self, node: ResearchNode) -> ResearchNode: ...


@runtime_checkable
class IUnitRepository(Protocol):
    async def list_by_country(self, country_id: int) -> list[Unit]: ...
    async def adjust(self, country_id: int, key: str, delta: int) -> Unit: ...
    async def create(self, **kwargs: Any) -> Unit: ...


@runtime_checkable
class IRegionRepository(Protocol):
    async def list_by_country(self, country_id: int) -> list[Region]: ...
    async def create(self, **kwargs: Any) -> Region: ...


@runtime_checkable
class IMarketRepository(Protocol):
    async def list_open_orders(self, world_id: int) -> list[MarketOrder]: ...
    async def list_by_country(self, country_id: int) -> list[MarketOrder]: ...
    async def create(self, **kwargs: Any) -> MarketOrder: ...
    async def update(self, order: MarketOrder) -> MarketOrder: ...
    async def matching_orders(self, world_id: int, side: MarketOrderSide, resource: str) -> list[MarketOrder]: ...


@runtime_checkable
class IWarRepository(Protocol):
    async def list_by_world(self, world_id: int) -> list[War]: ...
    async def list_active_for_country(self, country_id: int) -> list[War]: ...
    async def create(self, **kwargs: Any) -> War: ...
    async def update(self, war: War) -> War: ...


@runtime_checkable
class IDiplomacyRepository(Protocol):
    async def get(self, a: int, b: int) -> Diplomacy | None: ...
    async def list_for_country(self, country_id: int) -> list[Diplomacy]: ...
    async def upsert(self, diplo: Diplomacy) -> Diplomacy: ...


@runtime_checkable
class IAllianceRepository(Protocol):
    async def get(self, alliance_id: int) -> Alliance | None: ...
    async def list_by_world(self, world_id: int) -> list[Alliance]: ...
    async def create(self, **kwargs: Any) -> Alliance: ...
    async def members(self, alliance_id: int) -> list[Any]: ...
    async def add_member(self, alliance_id: int, country_id: int, role: Any) -> None: ...
    async def remove_member(self, alliance_id: int, country_id: int) -> None: ...


@runtime_checkable
class IMissionRepository(Protocol):
    async def list_by_country(self, country_id: int) -> list[Mission]: ...
    async def upsert(self, mission: Mission) -> Mission: ...


@runtime_checkable
class INotificationRepository(Protocol):
    async def list_by_player(self, player_id: int, limit: int = 50) -> list[Notification]: ...
    async def create(self, **kwargs: Any) -> Notification: ...
    async def mark_read(self, notification_id: int) -> bool: ...


@runtime_checkable
class IEventRepository(Protocol):
    async def list_by_world(self, world_id: int, limit: int = 50) -> list[GameEvent]: ...
    async def create(self, **kwargs: Any) -> GameEvent: ...


@runtime_checkable
class IOrderRepository(Protocol):
    async def list_pending(self, world_id: int, before: Any) -> list[Any]: ...
    async def create(self, **kwargs: Any) -> Any: ...
    async def mark_executed(self, order_id: int) -> None: ...
